### ISSUE TITLE
Board LEDs in Deep Sleep

### ISSUE THREAD

**Issue by jjloy314** [JakeS0ft/STREAM#3]
Hi-  I've noticed that the LED on the Nano and accelerometer stay on even when in Sleep Mode. Besides a kill key, is there a way to shut off these little vampires?

**Comment by JakeS0ft** [comment]
I'm afraid not. Protowerkstatt's "DIYino Stardust" boards have extra circuitry that allow for true deep sleep, but the BrewBoard and home-made setups still need to have a kill key or removable battery for long term storage. The deep sleep setting in STREAM will still put the CPU to sleep and put the MPU6050 in low power mode, so you'll save some power, but it's not a true deep sleep on home-brew hardware.

I seem to remember reading that one guy removed the LEDs from the modules, but that's really not an easy thing to do with those tiny surface mount parts.

**Comment by JakeS0ft** [comment]
Closing this issue since it is not within software scope.
