### ISSUE TITLE
Clash not detecting

### ISSUE THREAD

**Issue by ozzyrivera09** [JakeS0ft/STREAM#5]
Hi clash is not detecting on brewboard.
Everything else is working fine.

**Comment by JakeS0ft** [comment]
Some things to try:
1. Set the clash sensitivity to "9" using the in-hilt menu. This is the most sensitive. (See the user guide for details about how to do this.)
2. If that doesn't work, try setting the clash tolerance to a really small number (start with 10, then back it down from there) in the GUI's Motion Config screen. Save your settings, disconnect from the GUI, then select the "user custom" option when setting the clash sensitivity in the in-hilt menu.

It's also possible you have a bum MPU6050.

**Comment by JakeS0ft** [comment]
User has not reported any further information in over 20 days. Assuming the suggested fix worked. Closing this issue.
